name: OpenSSF Scorecard

on:
  push:         # Akan berjalan tiap kali ada commit baru
  schedule:     # Atur agar scan otomatis tiap minggu
    - cron: '0 0 * * 0'   # Mingguan setiap hari Minggu pukul 00.00 UTC

permissions:
  contents: read
  security-events: write  # Diperlukan untuk unggah hasil ke GitHub Code Scanning

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Run Scorecard
        uses: ossf/scorecard-action@v2.1.0
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload to code scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
